/**
 * Created by Saravana
 * This class contains all general constants variables.
 */

public with sharing class Constants {
    public final static String DEFAULT_CALC = 'Default';
    public final static String ADVANCE = 'Advance';
    public final static String CUSTOM = 'Custom';
    public final static String PACKAGE_CLASS_NAME = 'CalcAccountScorePackage';
    public final static String CREATE_ACCESS = 'Create';
    public final static String READ_ACCESS = 'Read';
    public final static String UPDATE_ACCESS = 'Edit';
    public final static String DELETE_ACCESS = 'Delete';
    public final static String UPSERT_ACCESS = 'Upsert';
}
